### ISSUE TITLE
rpi-64bit-meta shouldn't depend on dtbs USE flag on

### ISSUE THREAD

**Issue by andrey-utkin** [sakaki-/rpi3-overlay#19]
I have switched to kernel built from source, and disabled the `kernel-bin` USE flag in rpi-64bit-meta package.

This activates the conditional dependency on `sys-boot/rpi3-64bit-firmware` with `dtbs` flag being switched on: https://github.com/sakaki-/genpi64-overlay/blob/master/dev-embedded/rpi-64bit-meta/rpi-64bit-meta-1.5.2-r8.ebuild#L48

Which I think is wrong, because I installed my device tree files, including overlays, with my kernel.

**Comment by sakaki-** [comment]
Yes, I think on reflection you are correct about this. I'll drop the explicit dep in the next revbump (it is on by default for the `sys-boot/rpi3-64bit-firmware` package anyhow).

Thanks!

sakaki
