### ISSUE TITLE
Problem getting the repo to work with layman

### ISSUE THREAD

**Issue by FWiesner** [sakaki-/rpi3-overlay#23]
Hi,

I've added your overlay using layman
```layman -o https://raw.githubusercontent.com/sakaki-/genpi64-overlay/master/repositories.xml -a rpi3```

`rpi3` I've taken from your repositories.xml as ```layman -o https://raw.githubusercontent.com/sakaki-/genpi64-overlay/master/repositories.xml -a genpi64``` didn't work.

Adding the repo worked nicely, but then the sync fails because of repo name mismatch. Could you perhaps update your `repositories.xml`?

Thanks!

**Comment by sakaki-** [comment]
Yes, thanks for pointing this out. Will fix now.
Best, sakaki

**Comment by FWiesner** [comment]
thank you
