### ISSUE TITLE
Add use flag to rpi-64bit-meta to disable openrc related dependencies

### ISSUE THREAD

**Issue by jonesmz** [sakaki-/rpi3-overlay#25]
I'm trying to use systemd, and rpi-64bit-meta keeps trying to pull in openrc.

If there was a useflag to disable the dependency on sys-apps/rpi3-init-scripts-1.1.5-r1 it would be easier to do this.

**Comment by sakaki-** [comment]
Ack. I'm in the middle of putting together the next image release (with associated meta package bump) and will address this.
Best, S.

**Comment by jonesmz** [comment]
Thank you very much :-)

**Comment by sakaki-** [comment]
Done (`+init-scripts` USE [added in v1.5.4](https://github.com/sakaki-/genpi64-overlay/blob/c6c289db835418bbd4cb0cf54877ea74867f6c4a/dev-embedded/rpi-64bit-meta/rpi-64bit-meta-1.5.4-r5.ebuild#L55)).

Closing now. Best, sakaki
